### ISSUE TITLE
youtube-music audio only prevents app from loading

### ISSUE THREAD

**Issue by ThaUnknown** [cyfung1031/userscript-supports#52]
enabling yt:m audio only causes:
```log
watch?v=XzfWbi9xkgs:185 Uncaught TypeError: this.defineProperty322 is not a function
    at Object.defineProperty (watch?v=XzfWbi9xkgs:185:29)
    at da (music_polymer_inlined_html.js:10:730)
    at music_polymer_inlined_html.js:92:1
    at music_polymer_inlined_html.js:24480:289
```
which prevents the entire app from loading, unsure if the rest of the script works

**Comment by cyfung1031** [comment]
Fixed now. Please check and let me know whether it works.

**Comment by ThaUnknown** [comment]
you sir are doing gods work, fixed
